### PR TITLE
Fixing python versions in CI that is blocking merges

### PR DESCRIPTION
**Pull request by Mahfoudh94**

### CODE REVIEW

**Review by flrs — APPROVED** [review]

**Comment by flrs** [comment]
Thanks for these small but important edits!

**Comment by flrs** [comment]
Okay, I see failing tests. We didn't touch this in some time, so now we get in trouble for not having updated the deprecated np.float.

**Comment by Mahfoudh94** [comment]
yeah, sure buddy. thank you for developing such a library in the first place, its functionality is what brought me up here and it is fantastic.

**Comment by Mahfoudh94** [comment]
> ... the deprecated np.float.
as I see the problem is with np.NAN

**Comment by flrs** [comment]
You are welcome, thanks for your kind words! Happy to tag along with reviewing, if you have the resources to tackle the numpy type issue.

**Comment by flrs** [comment]
> > ... the deprecated np.float.
> 
> as I see the problem is with np.NAN
> 
> 

I see now, yes, that seems to be it, judging by the test logs.

**Comment by Mahfoudh94** [comment]
I see, yes, some of them are complaining about that too, so we have to replace all `np.NAN` instances with `np.nan`, and replace all `np.float`s with just `float`.
I am way too late tonight, and already closed the IDE, would you like to give it a try now, or wait for me to do it myself tomorrow?

**Comment by flrs** [comment]
Should be fixed with #32, please reopen/comment if you see it otherwise. Thank you for your contribution!

**Pull request closed without merging**
